# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LN9Vv1zXgIACPfWA-4LPhVlPFhxxgl6y
"""

!pip install opencv-python-headless

import cv2

vid = cv2.VideoCapture('3CYL_Flow.mp4')
success, image = vid.read()
count = 0

while success and count < 100:
    image = cv2.resize(image,(128,128))
    cv2.imwrite("/content/img/%d.png" % count, image)
    success, image = vid.read()
    count += 1

vid.release()
cv2.destroyAllWindows()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

import os
import numpy as np
import cv2

def add_gaussian_noise(image, mean=0, sigma=25):
    if image is None:
        return None

    row, col, ch = image.shape
    gauss = np.random.normal(mean, sigma, (row, col, ch))
    noisy_image = image + gauss
    return np.clip(noisy_image, 0, 255).astype(np.uint8)


def apply_noise_to_folder(folder_path, output_folder_path):
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            image = cv2.imread(image_path)

            if image is not None:
                noisy_image = add_gaussian_noise(image)
                output_path = os.path.join(output_folder_path, filename)
                cv2.imwrite(output_path, noisy_image)

            else:
                print(f"Error: Unable to load {filename}")

input_folder_path = "/content/img"

output_folder_path = "/content/noisyimage"

apply_noise_to_folder(input_folder_path, output_folder_path)

import os
import cv2
import numpy as np

def compute_mean(images):

    images_array = np.array(images)


    mean_image = np.mean(images_array, axis=0)
    return mean_image


def compute_covariance_matrix(images, mean_image):

    flattened_images = np.array(images) - mean_image
    flattened_images = flattened_images.reshape(flattened_images.shape[0], -1)


    covariance_matrix = np.dot(flattened_images.T, flattened_images) / flattened_images.shape[0]
    return covariance_matrix


def power_iteration(matrix, num_iterations=10):
    num_rows, num_cols = matrix.shape


    vector = np.random.rand(num_cols)

    for _ in range(num_iterations):
        vector = np.dot(matrix, vector)
        vector /= np.linalg.norm(vector)


    eigenvalue = np.dot(np.dot(vector.T, matrix), vector)
    return eigenvalue, vector


def pca(images, num_modes=None):
    images = [img for img in images if img is not None]
    if not images:
        print("Error: No valid images found.")
        return None, None, None


    mean_image = compute_mean(images)

    covariance_matrix = compute_covariance_matrix(images, mean_image)

    eigenvalues = []
    eigenvectors = []
    for _ in range(min(covariance_matrix.shape)):
        eigenvalue, eigenvector = power_iteration(covariance_matrix)
        eigenvalues.append(eigenvalue)
        eigenvectors.append(eigenvector)
        covariance_matrix -= eigenvalue * np.outer(eigenvector, eigenvector)

    modes = np.array(eigenvectors)
    if num_modes is not None:
        modes = modes[:num_modes]

    return mean_image, modes


def reconstruct_images(images, mean_image, modes):
    images_array = np.array(images)


    flattened_images = images_array.reshape(images_array.shape[0], -1)


    centered_images = flattened_images - mean_image.flatten()


    coefficients = np.dot(centered_images, modes.T)

    reconstructed_images = np.dot(coefficients, modes) + mean_image.flatten()


    reconstructed_images = reconstructed_images.reshape(images_array.shape)
    return reconstructed_images


def apply_pca_to_folder(input_folder_path, output_folder_path, num_modes=None, batch_size=64):
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)

    files = os.listdir(input_folder_path)
    image_files = [file for file in files if file.lower().endswith(('.png', '.jpg', '.jpeg'))][:10]
    if not image_files:
        print("Error: No image files found in the input folder.")
        return

    total_images = len(image_files)
    num_batches = total_images // batch_size
    if total_images % batch_size != 0:
        num_batches += 1

    for batch_index in range(num_batches):
        start_index = batch_index * batch_size
        end_index = min((batch_index + 1) * batch_size, total_images)

        batch_images = []
        for file in image_files[start_index:end_index]:
            image_path = os.path.join(input_folder_path, file)
            try:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                if image is None:
                    print(f"Error: Unable to read image {file}")
                    continue
                batch_images.append(image)
            except Exception as e:
                print(f"Error loading image {file}: {e}")

        mean_image, modes = pca(batch_images, num_modes)

        if modes is not None:
            reconstructed_images = reconstruct_images(batch_images, mean_image, modes)
            for image, filename in zip(reconstructed_images, image_files[start_index:end_index]):
                output_path = os.path.join(output_folder_path, filename)
                try:
                    cv2.imwrite(output_path, image)

                except Exception as e:
                    print(f"Error saving image {filename}: {e}")
        else:
            print("Error: Unable to perform PCA.")

input_folder_path = "/content/img"
output_folder_path = "/content/pod"

apply_pca_to_folder(input_folder_path, output_folder_path)

import os
import numpy as np
import cv2

def add_gaussian_noise(image, mean=0, sigma=25):
    if image is None:
        return None

    row, col, ch = image.shape
    gauss = np.random.normal(mean, sigma, (row, col, ch))
    noisy_image = image + gauss
    return np.clip(noisy_image, 0, 255).astype(np.uint8)


def apply_noise_to_folder(folder_path, output_folder_path):
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            image = cv2.imread(image_path)

            if image is not None:
                noisy_image = add_gaussian_noise(image)
                output_path = os.path.join(output_folder_path, filename)
                cv2.imwrite(output_path, noisy_image)
                print(f"Noise applied to {filename}")
            else:
                print(f"Error: Unable to load {filename}")


input_folder_path = "/content/pod"

output_folder_path = "/content/podnoisyimage"


apply_noise_to_folder(input_folder_path, output_folder_path)

import os
import numpy as np
import cv2

def add_gaussian_noise(image, mean=0, sigma=40):
    if image is None:
        return None

    row, col, ch = image.shape
    gauss = np.random.normal(mean, sigma, (row, col, ch))
    noisy_image = image + gauss
    return np.clip(noisy_image, 0, 255).astype(np.uint8)


def apply_noise_to_folder(folder_path, output_folder_path):
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            image = cv2.imread(image_path)

            if image is not None:
                noisy_image = add_gaussian_noise(image)
                output_path = os.path.join(output_folder_path, filename)
                cv2.imwrite(output_path, noisy_image)
                print(f"Noise applied to {filename}")
            else:
                print(f"Error: Unable to load {filename}")


input_folder_path = "/content/pod"

output_folder_path = "/content/podnoisyimage"


apply_noise_to_folder(input_folder_path, output_folder_path)

import os
import numpy as np
import cv2

def add_gaussian_noise(image, mean=0, sigma=80):
    if image is None:
        return None

    row, col, ch = image.shape
    gauss = np.random.normal(mean, sigma, (row, col, ch))
    noisy_image = image + gauss
    return np.clip(noisy_image, 0, 255).astype(np.uint8)


def apply_noise_to_folder(folder_path, output_folder_path):
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            image = cv2.imread(image_path)

            if image is not None:
                noisy_image = add_gaussian_noise(image)
                output_path = os.path.join(output_folder_path, filename)
                cv2.imwrite(output_path, noisy_image)
                print(f"Noise applied to {filename}")
            else:
                print(f"Error: Unable to load {filename}")


input_folder_path = "/content/pod"

output_folder_path = "/content/podnoisyimage"


apply_noise_to_folder(input_folder_path, output_folder_path)

import os
import cv2
import numpy as np

def apply_gaussian_filter(image, kernel_size=(5, 5), sigma=1.0):
    return cv2.GaussianBlur(image, kernel_size, sigma)

def apply_pod_to_folder(input_folder_path, output_folder_path, num_modes=None):
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)

    files = os.listdir(input_folder_path)
    image_files = [file for file in files if file.lower().endswith(('.png', '.jpg', '.jpeg'))][:100]
    if not image_files:
        print("Error: No image files found in the input folder.")
        return

    for file in image_files:
        image_path = os.path.join(input_folder_path, file)
        try:

            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            if image is None:
                print(f"Error: Unable to read image {file}")
                continue


            denoised_image = apply_gaussian_filter(image)

            # Save denoised image
            output_path = os.path.join(output_folder_path, file)
            cv2.imwrite(output_path, denoised_image)
            print(f"Denoised image saved: {output_path}")

        except Exception as e:
            print(f"Error processing image {file}: {e}")

# Paths to the input and output folders
input_folder_path = "/content/podnoisyimage"
output_folder_path = "/content/filterimage"

# Apply denoising using Gaussian filter to the first 100 images in the input folder
apply_pod_to_folder(input_folder_path, output_folder_path)

import os
import cv2
import numpy as np

def apply_gaussian_filter(image, kernel_size=(5, 5), sigma=1.0):
    return cv2.GaussianBlur(image, kernel_size, sigma)

def apply_pod_to_folder(input_folder_path, output_folder_path, num_modes=None):
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)

    files = os.listdir(input_folder_path)
    image_files = [file for file in files if file.lower().endswith(('.png', '.jpg', '.jpeg'))][:100]
    if not image_files:
        print("Error: No image files found in the input folder.")
        return

    for file in image_files:
        image_path = os.path.join(input_folder_path, file)
        try:

            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            if image is None:
                print(f"Error: Unable to read image {file}")
                continue


            denoised_image = apply_gaussian_filter(image)

            # Save denoised image
            output_path = os.path.join(output_folder_path, file)
            cv2.imwrite(output_path, denoised_image)
            print(f"Denoised image saved: {output_path}")

        except Exception as e:
            print(f"Error processing image {file}: {e}")

# Paths to the input and output folders
input_folder_path = "/content/podnoisyimage"
output_folder_path = "/content/filterimage"

# Apply denoising using Gaussian filter to the first 100 images in the input folder
apply_pod_to_folder(input_folder_path, output_folder_path)

